name: Kanji CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '30 11,23 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: |
          which java
          java --version
          echo "JAVA_HOME: ${JAVA_HOME}"
          find "${JAVA_HOME}" -type f
      - uses: actions/checkout@v2
      - name: Test (Debug)
        run: swift test -v --configuration debug
      - name: Test (Release)
        run: swift test -v --configuration release -Xswiftc -enable-testing

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Check JVM
        run: |
          which java
          java -version
          # /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64/Contents/Home
          echo "JAVA_HOME: ${JAVA_HOME}"
          echo "JRE_HOME: ${JRE_HOME}"

      - name: Test (Debug)
        run: |
          swift test -v --configuration debug -Xlinker -L${JAVA_HOME}/jre/lib/jli -Xlinker -rpath -Xlinker ${JAVA_HOME}/lib/jli -Xlinker -ljli

      - name: Test (Release)
        run: |
          swift test -v --configuration release -Xlinker -L${JAVA_HOME}/jre/lib/jli -Xlinker -ljli

  api-doc:
    runs-on: macos-12
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
        run: |
          swift -version
          export SWIFTPM_ENABLE_COMMAND_PLUGINS=1
          export DOCC_JSON_PRETTYPRINT="YES"

          # insert the docc dependency
          sed -I "" 's;^    dependencies: \[;    dependencies: [ .package(name: "swift-docc-plugin", url: "https://github.com/apple/swift-docc-plugin", from: "1.0.0"), ;1' Package.swift

          swift package --allow-writing-to-directory docs \
            generate-documentation --target KanjiVM \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path KanjiVM \
            --output-path docs \
            -Xlinker -L${JAVA_HOME}/jre/lib/jli -Xlinker -ljli

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '.'

