name: Kanji CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '30 11,23 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
          which java
          java --version
          echo "JAVA_HOME: ${JAVA_HOME}"
          find "${JAVA_HOME}" -type f

      - uses: actions/checkout@v4

      - name: Test (Debug)
        run: swift test --configuration debug

      - name: Test (Release)
        run: swift test --configuration release --parallel

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check JVM
        run: |
          which java
          java -version
          echo "JAVA_HOME: ${JAVA_HOME}"
          find "${JAVA_HOME}" -type f

      - name: Test (Debug)
        run: swift test --configuration debug

      - name: Test (Release)
        run: swift test --configuration release --parallel

